### ISSUE TITLE
unable to initpackage xscat in xspec

### ISSUE THREAD

**Issue by yaoyuhan** [AtomDB/xscat#1]
Hi -- I'm trying to use xscat to understand the effect of dust scattering. I follow the README file for installation and has completed the Main Code. I have heasoft version 6.27.2 installed (built from source code) on my Mac system.

After the step of 
XSPEC12>initpackage xscat model.dat .
I encountered an error of
calc_xscat.cxx:1:10: fatal error: 'XSUtil/FunctionUtils/funcType.h' file not found

However, the "funcType.h" file seems to be located at
/path/to/heasoft-6.27.2/Xspec/x86_64-apple-darwin17.7.0/include/funcType.h

May I know if there is something wrong in my installation?

Thanks!
Yuhan

**Comment by jagophile** [comment]
Thanks for the note. This is an issue due to the fact that XSPEC has moved a lot of the library files around as you found. I will fix this tomorrow, sorry I should have done this months ago.

**Comment by jagophile** [comment]
Sorry for the delay. I have just uploaded version 1.0.1 to github. This should now be resolved, let me know how you get on.

Thanks,
Adam

**Comment by yaoyuhan** [comment]
No error any more! Thanks!
